#global values can be overwritten by assigning after global import <<: *global
global: &global
  secure_scheme: true
  default_timeout: 5
  #retries
  api_call_retry_attempts: 5
  api_call_retry_interval: 3

api:
    host: http://localhost:3000


